# Generated by Django 5.1.6 on 2025-03-01 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivo', '0001_initial'),
        ('resguardante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
                ('no_serie', models.CharField(max_length=25, unique=True, verbose_name='# serie')),
                ('estado_fisico', models.CharField(max_length=150, verbose_name='Estado físico')),
                ('num_factura', models.CharField(max_length=30, verbose_name='# factura')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones / Comentarios')),
                ('created', models.DateField(auto_now=True, verbose_name='Creado')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivo.color')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivo.marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivo.modelo')),
                ('nombre_resguardante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resguardante.resguardante')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'inventario',
            },
        ),
    ]
